name: Create Release

on:
  push:
    tags:
    - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Create release name using the tag name
        run: |
             githubRef=${{ github.ref }}
             githubRef="${githubRef/'refs/tags'/''}"
             githubRef="${githubRef/'/'/''}"
             githubRef="${githubRef/'v'/''}"
             echo "releaseLabel=$githubRef" >> $GITHUB_ENV


      - name: Print release label
        run: echo $releaseLabel


      - name: Create release directory
        run: mkdir -p release/bin


    ### Generate jar file

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Install Maven
        run: sudo apt install maven


      - name: Check Maven Version
        run: mvn -version


      - name: Build jar using Maven
        run: mvn --batch-mode install verify -U -X


    ### Create zip file

      - name: Copy jar file from the dist to the release directory
        run: cp dist/javaxt-orm*.jar release/bin/javaxt-orm.jar


      - name: Copy release assets to the release directory
        run: cp -r src LICENSE.TXT release


      - name: Create zip file
        run: cd release; zip -r ../javaxt-orm_v${{ env.releaseLabel }}.zip *


    ### Upload zip file to javaxt.com

      - name: Upload release to server
        run: >-
          curl -X POST -L
          -H "Authorization: ${{ secrets.UPLOAD_AUTH }}"
          -F "file=@javaxt-orm_v${{ env.releaseLabel }}.zip;type=application/zip"
          "${{ secrets.UPLOAD_URL }}"

